name: Update AMI
on:
  workflow_dispatch:
  schedule:
    # First Tuesday of the month
    - cron: "0 0 1-7 * TUE"

jobs:
  update_ami:
    strategy:
      matrix:
        TF_DIR: [./terraform/env/prod]
    uses: CityOfPhiladelphia/citygeo-shared-workflows/.github/workflows/tf_ami_updater.yaml@main
    with:
      tf_dir: ${{ matrix.TF_DIR }}
      gh_app_id_keeper_path: ct0MNUfbMRs3dXCDJpjJUA/custom_field/app_id
      gh_app_private_key_keeper_path: ct0MNUfbMRs3dXCDJpjJUA/field/keyPair[0][privateKey]
      aws_access_key_id_keeper_path: 9Vi7qUgp2ht2JvmZRs-YXA/field/login
      aws_secret_access_key_keeper_path: 9Vi7qUgp2ht2JvmZRs-YXA/field/password
      pr_assignees: "Weastie"
    secrets: inherit
